--- #YAML:1.0
name:                FramesReady
version:             1.001
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::MD5:                   0
    HTML::HeadParser:              0
    MIME::Base64:                  2.1
    Net::FTP:                      2.58
    URI:                           1.10
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
