# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FramesReady
version:      1.016
version_from: lib/LWP/UserAgent/FramesReady.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    HTML::HeadParser:              0
    MIME::Base64:                  2.1
    Net::FTP:                      2.58
    URI:                           1.10

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
